name: Build & upload image

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download JMusicBot
        run: |
          URL=$(curl -s https://api.github.com/repos/jagrosh/MusicBot/releases/latest | grep -i browser_download_url.*\.jar | sed 's/.*\(http.*\)"/\1/')
          curl -L $URL -o JMusicBot.jar
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Renaud11232/jmusicbot
          tags: latest
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          #platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}